Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Development Machine - Ubuntu 18.04"

    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]

    vb.memory = 8192
    vb.cpus = 4
    vb.gui = true
  end

  config.vm.provision "shell", path: "scripts/00_install_packages.sh"
  config.vm.provision "shell", path: "scripts/01_setup_zsh.sh", privileged: false
  config.vm.provision "shell", path: "scripts/02_setup_dotfiles.sh", privileged: false
  config.vm.provision "shell", path: "scripts/03_set_password.sh"
  config.vm.provision "shell", path: "scripts/04_clone_git_repos.sh", privileged: false
  config.vm.provision "shell", path: "scripts/05_set_wallpaper.sh", privileged: false
end