Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Development Machine - Ubuntu 18.04"

    vb.memory = 1024
    vb.cpus = 2
    vb.gui = true
  end

  config.vm.provision "shell", path: "scripts/00_install_packages.sh"
  config.vm.provision "shell", path: "scripts/01_set_password.sh"
  config.vm.provision "shell", path: "scripts/02_clone_git_repos.sh"
end